spring.application.name=tesouraria
spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/tesouraria}
spring.datasource.username=${DB_USERNAME:usuario_app}
spring.datasource.password=${DB_PASSWORD:senha_db_local}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
jwt.secret=${JWT_SECRET:sua_chave_secreta_jwt_desenvolvimento_local_12345}
cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}
spring.jpa.show-sql: true
server.servlet.context-path=/
server.error.include-exception=false
server.error.include-stacktrace=never
spring.messages.basename=messages
